config/routes.rb
UploadDemo::Application.routes.draw do

  resources :upload_progress
  root :to => "upload_progress#index"

end

app/models/audio_file.rb
class AudioFile < ActiveRecord::Base

  has_attached_file :file

  validates_attachment_presence :file

  def self.generate_uid  
    DateTime::now.strftime("%H%M%L") 
    # naiv uid generation, it should involve user id etc to be more secure / uniq. for purpose of demo 
    # time is ok
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/upload_progress_controller.rb
class UploadProgressController < ApplicationController
  
  def index
  end

  def new
    @audio_file = AudioFile.new
    @uid = AudioFile::generate_uid
  end

  def create    
    request.format = :js
    @audio_file = AudioFile.new( params[:audio_file] )
    if @audio_file.save
      respond_to do |format|
        format.html{
          render :text => "wrong door"
        }
        format.js{ 
          render :json => {:path => @audio_file.file.url, :id => @audio_file.id }.to_json
        }
      end
    else
      render :json => { :errors => @audio_file.errors.full_messages },
             :status => 409
    end
  end 
  
  def update
    # in real life you should always check if item is this user not some prankster, current_user.audio_files.find
    @audio_file = AudioFile.find( params[:id] )
    if @audio_file.update_attributes(params[:audio_file])
      render :json => { :name => @audio_file.name },
             :status => 200 
    else
      render :json => { :errors => @audio_file.errors.full_messages },
             :status => 409
    end 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/upload_progress_helper.rb
module UploadProgressHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UploadDemo</title>
  <%= csrf_meta_tag %> 
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <%= stylesheet_link_tag "reset.css", "960.css", "application.css" %>
  <%= javascript_include_tag "jquery-1.4.2.min", "rails", "jquery.form", "application", "jquery.uploadProgress"  %>
</head>
<body>
  <div class="container_12">
     <div class="grid_8 alpha omega prefix_2 suffix_2 panel">
       <%= yield %>
     </div> 
  </div>

</body>
</html>

app/views/upload_progress/create.html.erb
<%= {:path => @audio_file.file.url}.to_json %>

app/views/upload_progress/index.html.erb
<h1>#index</h1>
<p>
  <%= link_to "try upload demo", new_upload_progres_path %>
</p>

app/views/upload_progress/new.html.erb
<h1>
   Welcome :)
</h1>                                 
<p>
   This demo is more proof-of-concept, X-Progress-ID is usable :).
</p>

<% form_for :audio_file, @audio_file, :url => upload_progress_path, 
                                      :html => { :multipart => true, :id => "audio-file-upload-form" } do |form| %> 
                                      
  <%= hidden_field_tag 'X-Progress-ID', @uid %>  
  <label for="audio_file_file">Select file</label>
  <%= form.file_field :file %>
  <%= submit_tag "Upload", :id => "audio-file-upload-form-submit" %>
<% end %>    

<% form_for :audio_file, @audio_file, :url => upload_progress_path, 
                                      :html => {:id => "audio-file-name-form", :class => "hidden-element", :method => :put} do |form| %>  
                                      
  <label for="audio_file_name">Enter file name:</label>                                       
  <%= form.text_field :name %>
<% end %>


<div id='progress' class='hidden-element'>
    File upload in progress            
    <div id='progress-bar' style='width: 0%;'>
        0%
    </div>
</div>             
                           
<p id="audio-file-name" class="hidden-element"></p>
<p id="audio-file-path" class="hidden-element"></p>      